export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const GET_SINGLE_PRODUCT_BEGIN = "GET_SINGLE_PRODUCT_BEGIN";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";

export const ADD_PRODUCT_IN_CARTS = "ADD_PRODUCT_IN_CARTS";
export const CLEAR_CARTS = "CLEAR_CARTS";
export const CLEAR_FORM = "CLEAR_FORM";

export const SHOW_CART = "SHOW_CART";
export const SHOW_MENU = "SHOW_MENU";
export const SHOW_PAY = "SHOW_PAY";

export const CHANGE_COUNT_FROM_CARTS = "CHANGE_COUNT_FROM_CARTS";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
